name: Gradle Build
on: [ push, pull_request ]

permissions: read-all

jobs:

  validate:
    name: "Validate gradle wrapper"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3

  build:
    name: "Build using Gradle"
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          check-latest: true
      - uses: gradle/actions/setup-gradle@v3
        with:
          # Read-only cache if not on repo's default branch: https://stackoverflow.com/a/68414395
          cache-read-only: ${{ format('refs/heads/{0}', github.event.repository.default_branch) != github.ref }}
      - run: ./gradlew build
      - uses: actions/upload-artifact@v4
        with:
          name: Build artifacts
          path: build/libs/*.jar